### ISSUE TITLE
Add MFA support

### ISSUE THREAD

**Issue by mkrichevsky** [danmx/sigil#27]
Add a tip to enter MFA code and used it if it's required for the aws profile being used

**Comment by efpe** [comment]
It works with `aws-vault`, vault will ask for your MFA code if configured properly:

```bash
aws-vault exec $AWS_PROFILE -- sigil -r eu-west-1 session --type instance-id --target i-xxxxxxxxxxxxxxxxx
```

**Comment by mkrichevsky** [comment]
This brings another dependency and increases complexity of usage. 
I'd like just to be prompted to enter MFA code and the tool should work after I enter it.

**Comment by danmx** [comment]
I've added MFA support in latest version. In PR https://github.com/danmx/sigil/pull/28
