### ISSUE TITLE
[BUG] Ctrl+c terminates sigil but leaves the session-manager-plugin running in the background

### ISSUE THREAD

**Issue by efpe** [danmx/sigil#39]
Sigil should not catch SIGINT but forward it to the session, e.g. ctrl+c should not kill the application. Also, when this happens the session-manager-plugin instance is left behind, so cleanup is not done properly.

```
$ sigil s --target i-0cb2ad893d6655405

Starting session with SessionId: 1556532435493310392-0e8d9c285c5f95f2e

sh-4.2$
^C
sh-4.2$ efpe@host  $

**Comment by danmx** [comment]
fixed in version `0.1.2`
