### ISSUE TITLE
[REQ] Add an option to list and modify (attach or terminate) active sessions

### ISSUE THREAD

**Issue by efpe** [danmx/sigil#40]
Would be nice to have an see all available sessions and be able to modify them.

**Comment by danmx** [comment]
Related to issue https://github.com/danmx/sigil/issues/34

**Comment by danmx** [comment]
Support for session termination added in https://github.com/danmx/sigil/pull/42

**Comment by danmx** [comment]
Released in version `0.2.0`

**Comment by danmx** [comment]
Only termination is supported
