### ISSUE TITLE
KMS encryption fails but works when using aws ssm start-session --target

### ISSUE THREAD

**Issue by aavileli** [danmx/sigil#46]
Encountered error while initiating handshake. KMSEncryption failed on client with status 2 error: Failed to process action KMSEncryption: Error calling KMS GenerateDataKey API: ValidationException: Invalid EncryptionContext
        status code: 400,

**Comment by danmx** [comment]
Could you describe your Session Manager configuration in AWS (e.g. logging) and the steps that you did?

I'll try to replicate it.

**Comment by aavileli** [comment]
Run As support enabled :false
KMS encryption enabled :true
KMS key ID : xxxxxx-xxxxx-xxxxx
S3 bucket storage enabled : true
Encrypt log data : true
S3 bucket name : xxx-xxx-xxxx.xxxx.xxxxx-x
S3 key prefix : uat/
CloudWatch log stream enabled: false

**Comment by danmx** [comment]
@aavileli try with new version `0.3.1` and please tell me if it's fixed for you

**Comment by aavileli** [comment]
works
