### ISSUE TITLE
ssh does not work with Ubuntu

### ISSUE THREAD

**Issue by aavileli** [danmx/sigil#49]
just hangs at this 
SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3

**Comment by danmx** [comment]
Did you check that you match all dependencies: https://github.com/danmx/sigil#external-dependencies

I had similar problem when I had an outdated `amazon-ssm-agent`.
Check if: 
- [ ] AWS session-manager-plugin is version 1.1.17.0+
- [ ] target EC2 instance have amazon-ssm-agent version 2.3.672.0+

**Comment by aavileli** [comment]
Have the latest version of both still the same 

Tried both commands :::
./sigil ssh --gen-key-pair --target i-xxxxxxx--log-level trace --os-user ubuntu
OR
./sigil ssh --pub-key ~/.ssh/ec2_xxxx.pub  --target i-xxxx --log-level trace --os-user ubuntu

Hangs at :::

> Starting session with SessionId: xxxx-058906xxxxxxx
> SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3

Version info :::
➜  ~ session-manager-plugin --version
1.1.23.0
 dpkg -l | grep ssm
ii  amazon-ssm-agent                2.3.680.0-1                       amd64        Amazon SSM Agent for

**Comment by danmx** [comment]
`sigil ssh` is designed to be used with `ProxyCommand` option not directly.

e.g.:
- `ssh -o ProxyCommand='./sigil ssh --gen-key-pair --target %h --log-level trace --os-user ubuntu --port %p' ubuntu@i-xxxxxxx`
- configured in your ssh configuration file ([ssh integration](https://github.com/danmx/sigil#ssh-integration)]

Also when using `gen-key` or `pub-key` options you need to have [`ec2instanceconnect`](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-set-up.html) installed on your host.

If you use all of that then please try to run `ssh` in verbose mode (`ssh -vvv`) and post the logs here.

**Comment by aavileli** [comment]
> mssh ubuntu@i-xxxxxx

 will successfully create a tmp ssh key and use the that temp key

The instructions for sigil need to be changed that for ubuntu you need to specify the ubuntu even if --os-user ubuntu is specified as it was trying my local logged in user

**Comment by danmx** [comment]
I was able to reproduce it. I'll try to find some time to fix it.

**Comment by danmx** [comment]
it seems it has the same problem even when using `aws-cli`:
```
ProxyCommand sh -c "aws ssm start-session --region eu-west-1 --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
```

I'd recommend raising an issue with AWS

**Comment by danmx** [comment]
In the end I've noticed that using `snap` installed older version of the agent.
I followed [instructions for Ubuntu 16.04 and 14.04](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html#agent-install-ubuntu-deb)

Finally I've ran it with:

- `amazon-ssm-agent` version `2.3.687.0`
- Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1044-aws x86_64)
- `session-manager-plugin` version `1.1.26.0`

and it worked for me.

If you still have the same problem feel free to reopen the issue.
